version: 1
update_configs:
  - package_manager: "javascript"
    update_schedule: "daily"
    directory: "."
    default_assignees:
      # update to your username :party:
      - "HugoDF"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
